### ISSUE TITLE
isnan and isinf out of scope

### ISSUE THREAD

**Issue by pranav9056** [jmodares/UB-ANC-Agent#1]
Hi Jalil,
There were a few compile errors when I cloned the UB-ANC-Agent repo. They mainly had to do with functions isnan() and isinf() being out of scope. Using them with std namespace fixed  the problem. 
Attaching the changes with the file names-
[https://github.com/pranav9056/UB-ANC-Agent/commit/572c0f55056e7d999c3495b279497092357efde4]
I can create a pull request if you don't want to modify them.
thanks

**Comment by jmodares** [comment]
Hi Pranav,

This is a known issue with new Linux distributions (gcc 4.8.x). Please go ahead and create a pull request.

Thanks,

**Comment by pranav9056** [comment]
sure, created the pull request, thanks
