### ISSUE TITLE
Confuse about how to edit each Agent's program

### ISSUE THREAD

**Issue by tsbiosky** [jmodares/UB-ANC-Agent#1]
Hi Dr .Modares

I am confused about how to use this emulator, for example i have three scripts for each drone ,I want the 3 drones follow the behavior that programmed  under the emulator .where should i put those 3 scripts and setup  ?

**Comment by nmastron** [comment]
Hi tsbiosky,

Did you have a chance to read through the UB-ANC Emulator's [wiki](https://github.com/jmodares/UB-ANC-Emulator/wiki)? In particular, we recommend that you go through the [quick start guide](https://github.com/jmodares/UB-ANC-Emulator/wiki#quick-start-guide) before trying to make any of your own missions.

If you have not gone through the quick start guide yet, then please take a look and let us know if that answers your question. If you have already gone through it, then could you please send us more information about the scripts you have for the drones? We are in the process of preparing more tutorials on coding missions, but we should be able to point you in the right direction to get you started.

**Comment by tsbiosky** [comment]
Yes I have gone through the quick start guide .I haven't write the script yet ,my plan is letting the drone autonomous fly in the emulator , I also confusing how to program the script ,I'm using Inter-aero, is python with dronekit  a good option ?
________________________________
发件人: nmastron <notifications@github.com>
发送时间: 2018年7月13日 11:01
收件人: jmodares/UB-ANC-Agent
抄送: tsbiosky; Author
主题: Re: [jmodares/UB-ANC-Agent] Confuse about how to edit each Agent's program (#1)


Hi tsbiosky,

Did you have a chance to read through the UB-ANC Emulator's wiki<https://github.com/jmodares/UB-ANC-Emulator/wiki>? In particular, we recommend that you go through the quick start guide<https://github.com/jmodares/UB-ANC-Emulator/wiki#quick-start-guide> before trying to make any of your own missions.

If you have not gone through the quick start guide yet, then please take a look and let us know if that answers your question. If you have already gone through it, then could you please send us more information about the scripts you have for the drones? We are in the process of preparing more tutorials on coding missions, but we should be able to point you in the right direction to get you started.

―

**Comment by nmastron** [comment]
Our system is not scripting based and does not currently work with dronekit. Instead, you will need to modify the UBAgent::missionTracker function in UBAgent.cpp (https://github.com/jmodares/UB-ANC-Agent/blob/master/agent/UBAgent.cpp). I recommend that you download the "clarity" branch of the UB-ANC-Agent software, since this code is better commented and should help you get started (however, we have not tested it yet on the actual drone, which is why we have not yet merged it with the master branch). I hope this helps!

**Comment by tsbiosky** [comment]
Thank you for your advice !
________________________________
发件人: nmastron <notifications@github.com>
发送时间: 2018年7月14日 21:56
收件人: jmodares/UB-ANC-Agent
抄送: tsbiosky; Author
主题: Re: [jmodares/UB-ANC-Agent] Confuse about how to edit each Agent's program (#1)


Our system is not scripting based and does not currently work with dronekit. Instead, you will need to modify the UBAgent::missionTracker function in UBAgent.cpp (https://github.com/jmodares/UB-ANC-Agent/blob/master/agent/UBAgent.cpp). I recommend that you download the "clarity" branch of the UB-ANC-Agent software, since this code is better commented and should help you get started (however, we have not tested it yet on the actual drone, which is why we have not yet merged it with the master branch). I hope this helps!

―
